file-save-path: D:\uploadFile\images\
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_qa?characterEncoding=UTF-8
    username: postgres
    password: root
    platform: postgresql
    separator: 
  sql:
    init:
      mode: always
      data-location: classpath:sql/config-data.sql
      schema-location: classpath:sql/config-schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://localhost:5432/my_qa?characterEncoding=UTF-8
# spring.datasource.username=postgres
# spring.datasource.password=root
# spring.datasource.platform=postgresql
# spring.datasource.separator=;
# spring.sql.init.mode=always
# spring.sql.init.data-location=classpath:sql/config-data.sql
# spring.sql.init.schema-location=classpath:sql/config-schema.sql
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
